/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Color;
import javaswingdev.FontAwesome;
import javaswingdev.FontAwesomeIcon;

/**
 *
 * @author RAVEN
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        label.setIcon(icon.toIcon());
        FontAwesomeIcon fontAwesome = new FontAwesomeIcon();
        fontAwesome.setIcon(FontAwesome.BOOK);
        label.setIcon(fontAwesome.toIcon());
        lb1.setIcon(icon1.toIcon());
        lb2.setIcon(icon2.toIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new javaswingdev.GoogleMaterialIcon();
        icon1 = new javaswingdev.GoogleMaterialIcon();
        icon2 = new javaswingdev.GoogleMaterialIcon();
        label = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();

        icon.setColor1(new java.awt.Color(255, 0, 204));
        icon.setColor2(new java.awt.Color(51, 51, 153));
        icon.setIcon(javaswingdev.GoogleMaterialDesignIcon.NOTIFICATIONS_ACTIVE);
        icon.setSize(200);

        icon1.setColor1(new java.awt.Color(0, 0, 70));
        icon1.setColor2(new java.awt.Color(28, 181, 224));
        icon1.setIcon(javaswingdev.GoogleMaterialDesignIcon.G_TRANSLATE);
        icon1.setSize(200);

        icon2.setColor1(new java.awt.Color(0, 153, 247));
        icon2.setColor2(new java.awt.Color(241, 23, 18));
        icon2.setIcon(javaswingdev.GoogleMaterialDesignIcon.LINKED_CAMERA);
        icon2.setSize(200);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label.setText(" ");

        lb1.setText(" ");

        lb2.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb2)
                .addContainerGap(879, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(lb1)
                    .addComponent(lb2))
                .addContainerGap(507, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaswingdev.GoogleMaterialIcon icon;
    private javaswingdev.GoogleMaterialIcon icon1;
    private javaswingdev.GoogleMaterialIcon icon2;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    // End of variables declaration//GEN-END:variables
}
